### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by rcprati** [conda-forge/qgis-feedstock#27]
Hi, I'm trying to install qgis in a fresh anaconda install in ubuntu but I having some troubles. 

First, it conflicted with anaconda-navigator:

> conda install qgis
> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - anaconda-navigator
>   - qgis
> Use "conda info <package>" to see the dependencies for each package.

I then removed anaconda-navigator, and new conflicts appear:

> conda install qgis
> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - anaconda -> mkl-service==1.1.2=py27hb2d42c5_4
>   - anaconda -> numexpr==2.6.4=py27hd318778_0
>   - anaconda -> scikit-learn==0.19.1=py27h445a80a_0
>   - qgis
> Use "conda info <package>" to see the dependencies for each package.

Any clues?

**Comment by ceholden** [comment]
Hi @rcprati! I'm on mobile so can't 100% confirm, but I'm pretty sure the issue stems from general incompatibilities between packages from the "defaults" channel and ones from "conda-forge" (see https://conda-forge.org/docs/conda-forge_gotchas.html). A program like QGIS with dozens of dependencies, including the GDAL stack, is pretty likely to encounter this sort of issue. Anaconda, which installs many packages from the "defaults" channel, increases the likelihood of running into incompatibilities that aren't easily resolved by the package manager. The QGIS 2.X series is also difficult because it relies on Qt4, while most of the rest of the Python ecosystem have moved onto Qt5 (though this will change with QGIS 3). 

I would first suggest trying to install QGIS into a conda environment so it can be isolated from the rest of your installation. This is good practice in general. You may also consider following the advice in the page I linked by moving "conda-forge" ahead of "defaults" in your channel priority. In general, you might also consider switching to the miniconda installer since so much of what comes with a full Anaconda install will be incompatible with conda-forge's packages. In practice the first thing I do with a new miniconda install is to upgrade so all packages from defaults get replaced with ones from conda-forge. 

Hope this helps. If you're still having issues, please reply and include a complete list of your installed packages with channel URLs (`conda list --show-channel-urls`).

**Comment by rcprati** [comment]
Hi @ceholden, I've put condo-forge as default channel, update, and them successfully install QGIS. Thanks for the tip.

Regards,

Ronaldo
 
--
