### ISSUE TITLE
Virtualenv problem, plus local paths left in code

### ISSUE THREAD

**Issue by adamczi** [conda-forge/qgis-feedstock#33]
Hi,
I installed miniconda2 + qgis2into my /opt folder (fresh Ubuntu 16.04.4 here), but can't run it. (I try to follow instructions to install Qgis2+3 alongside from http://narceliodesa.com/qgis-instalando-duas-versoes-diferentes-no-linux

this is what I get:

    adam@gs:/opt/miniconda2/bin$ ./qgis
    GLib-GIO-Message: 16:43:47.782: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
    Warning: loading of qgis translation failed [/opt/miniconda2/share/qgis/i18n//qgis_en_US]
    Warning: loading of qt translation failed [/home/carlos/miniconda/envs/_build/translations/qt_en_US]
    Warning: Object::connect: No such signal QgsMergedBookmarksTableModel::&QgsMergedBookmarksTableModel::selectItem( const QModelIndex &index )
    Warning: Object::connect:  (receiver name: 'QgsBookmarksBase')
    Warning: QCss::Parser - Failed to load file  "/style.qss" 
    QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
    Warning: QFileSystemWatcher: failed to add paths: /home/adam/.qgis2//project_templates
    Warning: QLayout: Attempting to add QLayout "" to QgsPanelWidgetStack "mWidgetStack", which already has a layout
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site.py", line 563, in <module>
        main()
      File "/usr/lib/python2.7/site.py", line 545, in main
        known_paths = addusersitepackages(known_paths)
      File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
        user_site = getusersitepackages()
      File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
       user_base = getuserbase() # this will also set USER_BASE
      File "/usr/lib/python2.7/site.py", line 237, in getuserbase
       USER_BASE = get_config_var('userbase')
      File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
        return get_config_vars().get(name)
      File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
        _init_posix(_CONFIG_VARS)
      File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
        from _sysconfigdata import build_time_vars
      File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
        from _sysconfigdata_nd import *
    ImportError: No module named _sysconfigdata_nd

Note:

1.  `/home/carlos/miniconda` path - no Carlos is present on my computer (greetings)
2. `/home/adam/.qgis2//project_templates` double slash path

Anyway, it seems that built-in Python is not really prepared to work, is there any way to change default Conda Python to my main system Python (or any else)? I prefer not to substitute conda/bin/python with symlink to my Python.

**Comment by ceholden** [comment]
Hi @adamczi 

If I'm understanding the main issue correctly, you want to have QGIS 2 from conda-forge while having QGS 3 from the Ubuntu repositories. Should be possible, but I think the key is that these two sources are maintained in isolation. Software compiled within the Conda (or conda-forge) ecosystem is unlikely to be compatible with your system libraries, so they shouldn't mix. For example, QGIS built from conda-forge should only run with the Python also from conda-forge. I'm guessing the issue relates to your PATH not being set to include the Conda installation's "bin" directory, or some other environment variable that makes Python inside QGIS to call your system Python instead of the one in /opt.

If this the problem, this example might help illustrate. For setup, installed QGIS into a "conda environment", which is the Conda ecosystem idea of a "virtualenv". I then navigated to where QGIS was installed, and tried to run it two ways -- without my PATH including the Conda installation, and with it.

``` bash
$ conda create -n test_qgis -c conda-forge qgis=2
$ cd ~/conda/envs/test_qgis/bin
$ ./qgis  # THIS DID NOT WORK
... error
$ PATH=$(pwd):$PATH ./qgis  # SUCCESS
```
in practice, it's probably generally beneficial and helpful for this issue to be using Conda environments. They help isolate your environment and are easy to create/import/export/delete. They also help me avoid having Conda's copies of Python and other executables in my PATH because I can just symlink `activate`, `deactivate`, and `conda` into my PATH (specifically, `$HOME/bin`). Given the setup showed above:

``` bash
$ source ~/conda/bin/activate test_qgis
$ which qgis
~/conda/bin/qgis
$ which python
~/conda/bin/python
$ qgis  # SUCCESS
```

Hope this is helpful to you. If not, would you include the output of the `env` command which would show the order of your PATH and other relevant variables (you might want to make sure there's no sensitive information stored).


For your notes, I think the first is caused from the `qt` package, which has to be hand compiled because it takes too long for the continuous integration services. We had to patch something to make QGIS avoid using the path it was built from, and I think we can patch [qgsapplication.cpp ~L763](https://github.com/qgis/QGIS/blob/master/src/core/qgsapplication.cpp#L763) to do similar for translations. For your second note, does the double slash cause an issue? I haven't ever used templates. I poked around in QGIS's source code and it looks like they add it intentionally.

**Comment by adamczi** [comment]
Hi, thanks for your response. This indeed was not a problem on your side, sorry for the mess here. The key was what you suggested, to install qgis2 into an environment, which I didn't do before. 

At this point QGIS 2 works, but what I found was invasive is PATH after miniconda installation - I get their `bin` path to the beginning of PATH, which I don't think they should do, so I couldn't run my QGIS3 before fixing it.
About notes: you're right, false alarms. Once again thanks for your support.
