### ISSUE TITLE
Install GDAL lib for geoparquet support by default?

### ISSUE THREAD

**Issue by ThomasG77** [conda-forge/qgis-feedstock#422]
### Comment:

While using qgis from conda, I was at first unable to open Geoparquet files. Installing additional `libgdal-arrow-parquet` package within the environment, it works fine.
Although I was able to sort out the problem, is it possible to make the package a dependency from qgis package? It adds 15MB for the install but can avoid users to search why geoparquet not working within their qgis conda install.

**Comment by gillins** [comment]
@ThomasG77 we had some discussion about this here: https://github.com/conda-forge/qgis-feedstock/pull/386. We are following GDAL's lead here, and personally I'm not keen on making the install too much larger. Maybe take it up with the gdal-feedstock since this applies equally to all packages that use GDAL.
However, I would be open to creating a `qgis-full` package with all these optional packages installed. Or a `qgis-minimal` that I could use and `qgis` that has all the extra. Any thoughts @conda-forge/qgis ?

**Comment by ThomasG77** [comment]
Thanks for the feedback. I did miss the discussion. Reading it was a good thing. It seems I'm too biased by my high speed connection and being a "too early adopter" whereas most people may not care about this particular driver before some years in "main" population. So, the proposition mentioned in the the other discussion is fine for me e.g

> @SrNetoChan is putting together a list of useful optional packages that "may work well with QGIS" for us to display on installation, hopefully this may assist the novice user.
